services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - SERVICE_FQDN_KAVITA_5000
    volumes:
      - config:/config
      - /mnt/data/Multimedia/Manga:/data
    ports:
      - 5000:5000
    restart: unless-stopped
